version: "3.8"
services:

  api-gateway:
    build: ./api/api-gateway
    ports:
      - "8080:80"
    depends_on:
      - auth
      - restaurant
      - order
      - delivery
      - payment
      - notification

  auth:
    build: ./api/auth-service
    env_file: ./api/auth-service/.env
    ports:
      - "3000:3000"

  restaurant:
    build: ./api/restaurant-service
    env_file: ./api/restaurant-service/.env
    ports:
      - "3001:3001"
    depends_on:
      - auth

  order:
    build: ./api/order-service
    env_file: ./api/order-service/.env
    ports:
      - "3002:3002"
    depends_on:
      - auth
      - restaurant

  delivery:
    build: ./api/delivery-service
    env_file: ./api/delivery-service/.env
    ports:
      - "3003:3003"
    depends_on:
      - auth
      - order
      - restaurant

  payment:
    build: ./api/payment-service
    env_file: ./api/payment-service/.env
    ports:
      - "3005:3005"
    depends_on:
      - auth
      - order

  notification:
    build: ./api/notification-service
    env_file: ./api/notification-service/.env
    ports:
      - "3006:3006"
    depends_on:
      - auth
