apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: food-delivery
  labels:
    app: auth-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
      - name: auth
        image: auth-service:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
        envFrom:
        - secretRef:    { name: auth-secrets }
        - configMapRef: { name: auth-config }
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: food-delivery
spec:
  selector:
    app: auth-service
  ports:
    - port: 3000
      targetPort: 3000
  type: ClusterIP
