# k8s/delivery.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: delivery-service
  namespace: food-delivery
  labels:
    app: delivery-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: delivery-service
  template:
    metadata:
      labels:
        app: delivery-service
    spec:
      containers:
      - name: delivery
        image: delivery-service:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3003
        envFrom:
        - secretRef:    { name: delivery-secrets }
        - configMapRef: { name: delivery-config }
---
apiVersion: v1
kind: Service
metadata:
  name: delivery-service
  namespace: food-delivery
spec:
  selector:
    app: delivery-service
  ports:
  - port: 3003
    targetPort: 3003
  type: ClusterIP
