# k8s/notification.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
  namespace: food-delivery
  labels:
    app: notification-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
      - name: notification
        image: notification-service:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3006
        envFrom:
        - secretRef:    { name: notification-secrets }
        - configMapRef: { name: notification-config }
---
apiVersion: v1
kind: Service
metadata:
  name: notification-service
  namespace: food-delivery
spec:
  selector:
    app: notification-service
  ports:
  - port: 3006
    targetPort: 3006
  type: ClusterIP
