# k8s/payment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
  namespace: food-delivery
  labels:
    app: payment-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
    spec:
      containers:
      - name: payment
        image: payment-service:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3005
        envFrom:
        - secretRef:    { name: payment-secrets }
        - configMapRef: { name: payment-config }
---
apiVersion: v1
kind: Service
metadata:
  name: payment-service
  namespace: food-delivery
spec:
  selector:
    app: payment-service
  ports:
  - port: 3005
    targetPort: 3005
  type: ClusterIP
