# k8s/restaurant.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: restaurant-service
  namespace: food-delivery
  labels:
    app: restaurant-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: restaurant-service
  template:
    metadata:
      labels:
        app: restaurant-service
    spec:
      containers:
      - name: restaurant
        image: restaurant-service:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3001
        envFrom:
        - secretRef:    { name: restaurant-secrets }
        - configMapRef: { name: restaurant-config }
---
apiVersion: v1
kind: Service
metadata:
  name: restaurant-service
  namespace: food-delivery
spec:
  selector:
    app: restaurant-service
  ports:
  - port: 3001
    targetPort: 3001
  type: ClusterIP
